Repository repl-cli/REPL, pull requests merged in 2022-10, with the labels that each got.

#2 Add the typescript module
  .travis.yml
  config
  config.default
  language_support.sh
  repl_modules.sh
  test/modules_test.sh
Labels: enhancement

#3 Release: Update documentation and prepare for new release
  CONTRIBUTING.md
  README.md
  install.sh
Labels: enhancement, hacktoberfest-accepted

#4 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug

#6 Adds support for Go Lang
  README.md
  config
  config.default
  language_support.sh
  repl_modules.sh
  test/modules_test.sh
Labels: enhancement, hacktoberfest-accepted

#5 Adds `Repl Languages` command to list all supported languages; Update missing language in readme
  README.md
  bin/repl
  test/main_test.sh
Labels: enhancement

#9 Add c sharp support
  README.md
  config
  config.default
  language_support.sh
  modules/boilerplates/repl.cs
  modules/repl_modules.sh
  test/modules_test.sh
Labels: enhancement, hacktoberfest-accepted

#12 feat: add Swift lang support
  README.md
  config
  config.default
  language_support.sh
  modules/boilerplates/repl.swift
  modules/repl_modules.sh
  test/modules_test.sh
Labels: enhancement, hacktoberfest-accepted
